# Generated by Django 5.0.1 on 2024-02-04 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow_books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowmodel',
            name='is_borrow',
        ),
        migrations.AddField(
            model_name='borrowmodel',
            name='book_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='borrowmodel',
            name='book_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='borrowmodel',
            name='borrow_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
