# Generated by Django 5.0.1 on 2024-02-04 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('borrow_books', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('comment', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='books/media/uploads/')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('borrow_books', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='borrow_books.borrowmodel')),
                ('category', models.ManyToManyField(to='categories.categorymodel')),
            ],
        ),
    ]
