# Generated by Django 5.0.1 on 2024-02-04 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_bookmodel_borrow_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
