# Generated by Django 5.0.1 on 2024-02-04 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_bookmodel_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.RemoveField(
            model_name='bookmodel',
            name='borrow_books',
        ),
    ]
